version: '3.1'
services:
  app:
    container_name: springboot-postgresql
    image: springboot-postgresql
    build: ./
    ports:
      - "8081:8081"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5050:5050"
    environment:
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=Telegram_Notification